name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
- type: textarea
  id: behavior
  attributes:
    label: What happened?
    placeholder: Describe the unintended behaviour.
    value: ""
  validations:
    required: true
- type: textarea
  id: expected-behavior
  attributes:
    label: What should've happened?
    placeholder: Describe the correct behaviour.
  validations:
    required: true
- type: input
  id: version
  attributes:
    label: Version
    description: What version of zeal-cli are you running?
  validations:
    required: true
- type: dropdown
  id: build
  attributes:
    label: Build
    options:
      - Downloaded from Release
      - make build
      - make <linux/windows>-install
      - Other (please explain in the What Happened? section)
  validations:
    required: true
- type: input
  id: os
  attributes:
    label: OS
    description: What OS (and version) are you running?
  validations:
    required: true
- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
    options:
      - label: I agree to follow this project's Code of Conduct
        required: true
