name: Feature Request
description: File a bug report
title: "[Feature]: "
labels: ["enhancement"]
body:
- type: textarea
  id: request
  attributes:
    label: Feature Request
    placeholder: Describe the feature you would like added.
    value: "Feature Request"
  validations:
    required: true
- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](https://blog.morpheus636.com/code-of-conduct)
    options:
      - label: I agree to follow this project's Code of Conduct
        required: true
