name: Build Binaries

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os[0]}}

    strategy:
      matrix:
        os: [[ubuntu-latest, linux]]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - run: git fetch --prune --tags --unshallow

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"

      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v7

      - name: Install Poetry Packages
        run: poetry install

      - name: Build Pyinstaller
        run: make build

      - name: Upload Executables
        uses: softprops/action-gh-release@v0.1.14
        with:
          files: |
            dist/zeal-cli
            dist/zeal-cli.exe
