name: Build Binaries

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - run: git fetch --prune --tags --unshallow

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"

      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v7

      - name: Install Poetry Packages
        run: poetry install

      - name: Get version
        run: |
          poetry run python ./build_system/update_version.py

      - name: Build Pyinstaller
        run: |
          poetry run python ./build_system/update_version.py
          poetry run pyinstaller --onefile ./src/zeal_cli.py --name zeal-cli

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: zeal-cli
          path: dist/zeal-cli
          retention-days: 5
        if: matrix.os == 'ubuntu-latest'

      - name: 'Upload Artifact - Windows'
        uses: actions/upload-artifact@v3
        with:
          name: zeal-cli.exe
          path: dist/zeal-cli.exe
          retention-days: 5
        if: matrix.os == 'windows-latest'

  release:
    needs: build

    runs-on: "ubuntu-latest"

    steps:
      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          path: /home/runner/artifacts

      - name: Upload Executables
        uses: softprops/action-gh-release@v0.1.14
        with:
          files: |
            /home/runner/artifacts/**/zeal-cli
            /home/runner/artifacts/**/zeal-cli.exe
          fail_on_unmatched_files: true