name: Build for PyPi

on:
  push:
    tags:
      - "v*"
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v7

      - name: Install Packages
        run: poetry install --no-dev

      - name: Build
        run: poetry build

      - name: Publish
        run: poetry publish -u ${{ secrets.PYPI_USER}} -p ${{ secrets.PYPI_PASS}}
